packages:
  - "app"
  - "tools"
  - "tests"
  - "options"
  - "snap"
  - "prisma"
  - "package/node"
  - "package/github"
  - "package/vscode"
  - "package/cli/web"
  - "docs"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
